--- 
title: "Interactive Features of Open Actuarial Textbooks"
author: "An open project authored by the Actuarial Community"
site: bookdown::bookdown_site
output:
  bookdown::gitbook
documentclass: book
link-citations: yes
github-repo: https://github.com/OpenActTextDev/InteractiveFeatures

---

# Preface {-}

<p style="text-align:right;">
*Date: `r format(Sys.Date(), "%d %B %Y")`*</p>


#### Use of *R* as a Tool for Interactive Books and Short Courses {-}

There are many great tools that have been developed to author books (e.g., Word, latex) and interactive short courses (e.g., Wordpress). However, we are using `R` as a tool for writing (books and webpages) through its **markdown** capabilities, including the package `bookdown`. The use of `R` is well known in the actuarial community - we hope that promoting its application for authoring our books and short courses will help in recruiting a broad and sustainable group of authors and other volunteers from the actuarial community.

 Here is a list of pieces of the project:

*  See the [Open Actuarial Textbooks Project Site](https://sites.google.com/a/wisc.edu/loss-data-analytics/) for more information about this project.
*  [Loss Data Analytics Landing Site](https://openacttexts.github.io/)
   *  [*Loss Data Analytics*](https://openacttexts.github.io/Loss-Data-Analytics/index.html) is an interactive, online, freely available text.
   *  [Offline versions of the *Loss Data Analytics*](https://ewfrees.github.io/Loss-Data-Analytics/DownloadOffline.html) book, in **pdf** and **epub**
   *  [Spanish version of *Loss Data Analytics*](https://openacttexts.github.io/LDASpanish/)
   *  [R Code to support *Loss Data Analytics*](https://openacttexts.github.io/LDARcode)
*  A [Style Guide](https://OpenActTexts.github.io/StyleGuideLDA/index.html) (prospective contributors should check this out)
*  [Short Course on Loss Data Analytics](https://openacttexts.github.io/LDACourse1/)
*  [Github Development Site](https://github.com/OpenActTextDev)
   *  [*Life Contingencies*](https://openacttextdev.github.io/LifeCon/), under development

#### Interactive Features {-}

This document describes interactive features of the *Open Actuarial Textbooks* project that are being developed, in process, and in the planning stages. By **interactive features**, we start with simple things like layering content (such as Show/Hide way of displaying code below) and move on from there.


<h5 style="text-align: center;"><a id="display.T:Frequency.1Intro" href="javascript:togglecode
('display.T:Frequency.2Intro','display.T:Frequency.1Intro');"><i><strong>R Code for Frequency Table</strong></i></a> </h5>
<div id="display.T:Frequency.2Intro" style="display: none">

```
Insample <- read.csv("Insample.csv", header=T,  na.strings=c("."), stringsAsFactors=FALSE)
Insample2010 <- subset(Insample, Year==2010)
table(Insample2010$Freq)
```
</div>

#### Why Now? {-}

It might be helpful to organize these efforts under the umbrella of the [Astin Academy](https://www.actuaries.org/IAA/IAA/Sections/ASTIN_NEW/Our_Activities.aspx?WebsiteKey=ff59269c-4928-4369-a169-03e74a6bd8ca&hkey=b94800cc-f36d-4bb0-a49c-0d0b1d761d7f&New_ContentCollectionOrganizerCommon=8#New_ContentCollectionOrganizerCommon).

##### Mission of ASTIN Academy {-}

*The mission of the ASTIN Academy is to provide high quality free educational materials in non-life insurance to actuarial students across the world. The Academy is committed to open course development under Creative Commons license and seeks innovation in teaching methodologies and application of technology. Let’s build the future of actuarial education together.*



  

